package com.example.fulbot.botapi;

public enum BotState {
    ASK_DELIVERY,
    ASK_BOX_QUANTITY,
    ASK_ITEM_QUANTITY,
    ASK_DEFECTIVE,
    ASK_SMART_DEFECTIVE,
    ASK_BARCODE,
    ASK_PACKAGING,
    ASK_PACKAGING_PRICE,
    ASK_MARKET_DELIVERY,
    ASK_PREPARE_BOXES,
    ASK_AGREE,
    ASK_PHONE,
    FINISH,
    SHOW_CALCULATIONS,
    DELETE_CALCULATIONS
}
